# Support the author by using the funding links below.
# Developed and maintained by M1CK431 with the help of awesome contributors.
# Buy Me a Coffee: https://buymeacoffee.com/m1ck431

buy_me_a_coffee: m1ck431

# Sponsoring this project means a lot to me, this will help me to continue building great open-source projects just like this.